### ISSUE TITLE
Practical usage documentation

### ISSUE THREAD

**Issue by viraptor** [buildkite/elastic-ci-stack-s3-secrets-hooks#83]
When using the secrets with the buildkite docker plugin, the secrets are not automatically propagated. Specifically:
```
    plugins:
      - docker#v3.11.0:
          image: "..."
          propagate_environment: true
```
will not use the secrets. Instead the developer needs to explicitly add:
```
          environment:
            - THE_SECRET
```
This is unintuitive and could use a note in the README here with an example how that interaction works.
